"""add postings.source_updated_at

Revision ID: 13c2203d963b
Revises: ee344d1a094c
Create Date: 2026-06-21 09:43:43.500977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c2203d963b'
down_revision: Union[str, Sequence[str], None] = 'ee344d1a094c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.drop_column('source_updated_at')

    # ### end Alembic commands ###
