"""add postings.in_scope

Revision ID: d30501b4c8ab
Revises: f7164d547f15
Create Date: 2026-06-22 14:02:51.524824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30501b4c8ab'
down_revision: Union[str, Sequence[str], None] = 'f7164d547f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_scope', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.drop_column('in_scope')

    # ### end Alembic commands ###
