"""initial schema

Revision ID: ee344d1a094c
Revises: 
Create Date: 2026-06-15 19:07:34.224827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee344d1a094c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('vertical', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='digest_status', native_enum=False), server_default='pending', nullable=False),
    sa.Column('contents', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vertical', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('key_cities', sa.String(), nullable=True),
    sa.Column('role_tilt', sa.String(), nullable=True),
    sa.Column('ats_type', sa.Enum('greenhouse', 'lever', 'ashby', 'workday', 'icims', 'workable', 'oracle_hcm', 'smartrecruiters', 'jobvite', 'successfactors', 'avature', 'ukg', 'eightfold', 'radancy', 'custom', 'raw_html', 'unknown', name='ats_type', native_enum=False), nullable=False),
    sa.Column('ats_slug', sa.String(), nullable=True),
    sa.Column('careers_url', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'agent_discovered', name='employer_source', native_enum=False), server_default='manual', nullable=False),
    sa.Column('status', sa.Enum('proposed', 'approved', 'active', 'retired', name='employer_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('verification', sa.Enum('verified', 'detected', 'layer2', name='verification', native_enum=False), nullable=True),
    sa.Column('early_career_volume_estimate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vertical', 'name', name='uq_employers_vertical_name')
    )
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.create_index('ix_employers_vertical_status', ['vertical', 'status'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'ok', 'partial', 'failed', name='pipeline_run_status', native_enum=False), nullable=False),
    sa.Column('employers_fetched', sa.Integer(), nullable=True),
    sa.Column('fetch_failures', sa.Integer(), nullable=True),
    sa.Column('postings_new', sa.Integer(), nullable=True),
    sa.Column('postings_closed', sa.Integer(), nullable=True),
    sa.Column('extraction_calls', sa.Integer(), nullable=True),
    sa.Column('match_calls', sa.Integer(), nullable=True),
    sa.Column('llm_cost_usd', sa.Float(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('vertical', sa.String(), nullable=False),
    sa.Column('resume_version', sa.String(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('domain_vocabulary', sa.JSON(), nullable=True),
    sa.Column('active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vertical', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('hn_whoishiring', 'niche_board', 'newsletter', name='source_kind', native_enum=False), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('ingestion_method', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='posting_status', native_enum=False), server_default='open', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('level', sa.Enum('intern', 'new_grad', 'early_career', 'mid', 'senior', 'unknown', name='level', native_enum=False), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('remote', sa.Enum('onsite', 'hybrid', 'remote', 'unknown', name='remote_type', native_enum=False), nullable=True),
    sa.Column('work_auth', sa.String(), nullable=True),
    sa.Column('stack', sa.JSON(), nullable=True),
    sa.Column('comp_min', sa.Integer(), nullable=True),
    sa.Column('comp_max', sa.Integer(), nullable=True),
    sa.Column('comp_raw', sa.String(), nullable=True),
    sa.Column('posted_at', sa.Text(), nullable=True),
    sa.Column('extraction_model', sa.String(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(employer_id IS NULL) <> (source_id IS NULL)', name='ck_postings_employer_xor_source'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employer_id', 'external_id', name='uq_postings_employer_external'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_postings_source_external')
    )
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.create_index('ix_postings_employer_status', ['employer_id', 'status'], unique=False)
        batch_op.create_index('ix_postings_status_first_seen', ['status', 'first_seen_at'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('resume_version', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.Enum('strong_yes', 'yes', 'maybe', 'no', name='verdict', native_enum=False), nullable=False),
    sa.Column('fits', sa.Text(), nullable=True),
    sa.Column('gaps', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('trigger', sa.Enum('nightly', 'backfill', 'refresh', name='match_trigger', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('posting_id', 'profile_id', 'resume_version', name='uq_matches_posting_profile_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.drop_index('ix_postings_status_first_seen')
        batch_op.drop_index('ix_postings_employer_status')

    op.drop_table('postings')
    op.drop_table('sources')
    op.drop_table('profiles')
    op.drop_table('pipeline_runs')
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.drop_index('ix_employers_vertical_status')

    op.drop_table('employers')
    op.drop_table('digests')
    # ### end Alembic commands ###
