"""add ix_postings_status_source_updated

Revision ID: f7164d547f15
Revises: 13c2203d963b
Create Date: 2026-06-21 11:04:23.653394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7164d547f15'
down_revision: Union[str, Sequence[str], None] = '13c2203d963b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.create_index('ix_postings_status_source_updated', ['status', 'source_updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.drop_index('ix_postings_status_source_updated')

    # ### end Alembic commands ###
